version: '3'
services:
  filedrop:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_APP_NAME=${APP_NAME}
    environment:
      - WS_HOST=0.0.0.0
      - WS_APP_NAME=${APP_NAME}
      - WS_ABUSE_EMAIL=${ABUSE_EMAIL}
      - WS_USE_X_FORWARDED_FOR=${USE_X_FORWARDED_FOR}
      - WS_REQUIRE_CRYPTO=${REQUIRE_CRYPTO}
      - TURN_MODE=hmac
      - TURN_SERVER=turn:(hostname)
      - TURN_USERNAME=filedrop
      - TURN_SECRET=${TURN_SECRET}
    ports:
      - '${PORT}:5000'

  coturn:
    image: coturn/coturn
    command:
      - --log-file=stdout
      - --use-auth-secret
      - --static-auth-secret=${TURN_SECRET}
      - --no-multicast-peers
      - --no-tls
      - --no-dtls
      - --no-software-attribute
      - --fingerprint
      - --no-cli
    network_mode: host
    depends_on:
      - filedrop
